server:
  port: 80
spring:
  application:
    name: iot-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务发现
    gateway:
      routes:
        - id: sys_manager
          uri: lb://system-manager
          predicates: #断言，路径相匹配的才会进行uri/Path的路由
            - Path=/sys/**

        - id: model-manager
          uri: lb://model-manager
          predicates:
            - Path=/model/**
        - id: item-manager
          uri: lb://item-manager
          predicates:
            - Path=/item/**
        - id: asset-manager
          uri: lb://asset-manager
          predicates:
            - Path=/asset/**

        - id: alarm-manager
          uri: lb://alarm-manager
          predicates:
            - Path=/alarm/**
        - id: monitor-manager
          uri: lb:ws://monitor-manager
          predicates:
            - Path=/monitor/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由