server:
  port: 8006
spring:
  application:
    name: message-send
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/iot # 数据库名称
    username: root
    password: 123
  cloud:
     nacos:
       discovery:
         server-addr: 175.27.245.91:8848 #nacos地址
  redis:
   host: 175.27.245.91
   port: 6379
   lettuce:
     pool:
       max-active: 8
       max-idle: 8
       max-wait: -1ms
       min-idle: 1
  kafka:
    producer:
      bootstrap-servers: 175.27.245.91:9092
      value-serializer: xg.beans.AlarmSeria
    consumer:
      bootstrap-servers: 175.27.245.91:9092
      auto-offset-reset: earliest
      value-deserializer: xg.beans.AlarmDes

mybatis:
  type-aliases-package: xg.beans #所有Entity别名类所在包
  mapper-locations: [classpath:mapper/**/*.xml]